# Generated by Django 6.1.1 on 2026-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('category', models.CharField(choices=[('bombons', 'Bombons'), ('tabletes', 'Tabletes'), ('presentes', 'Presentes'), ('especiais', 'Especiais')], max_length=20, verbose_name='categoría')),
                ('image', models.ImageField(upload_to='products/', verbose_name='foto')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['category', 'name'],
            },
        ),
    ]
