# Generated by Django 6.1.1 on 2026-09-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='foto alternativa'),
        ),
    ]
